name: 'Morrisey & Co.'
favicon: null
layout_spectrum: 0.7511663096956909
typography_spectrum: 0.6093008725438267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.862323246197775
  lightness: 0.7962509184144437
  saturation: 0.6137240121606737
  rhythmicContrast: 0.6583616549614817
purpose: []
