purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8651987
  brandStrength: 1
  lightness: 0.6707841
  brandColors:
    - '#FFFFFF'
    - '#151515'
    - '#4C5C6D'
    - '#FCBF7E'
    - '#717A8B'
  rhythmicContrast: 0.8319011
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Morrisey & Co.
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9081632
layout_spectrum: 0.0209452
